baseURL = "https://denvasyukov07-beep.github.io/URBA-SPORK/"
languageCode = "ru-ru"
title = "SimplePhysics"
theme = "PaperMod"
relativeURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ["warning-goldmark-raw-html"]

[params]
  env = "production"